name: build

on:
  push:
    branches:
      - main

jobs:
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with: {submodules: true}
      - name: Run the test suite
        uses: actions-rs/cargo@v1
        with: {command: test, args: --features=bundled --verbose}

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with: {submodules: true}
      - name: Run the test suite
        uses: actions-rs/cargo@v1
        with: {command: test, args: --features=bundled --verbose}
